name: Auto-Generate Docs Sidebar

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'           # 任何文档变化都触发

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write       # 允许推回仓库
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 选项 A：使用 CLI（简单）
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm i -D docsify-generate-sidebar
      - run: npx docsify-generate-sidebar docs docs/_sidebar.md --ignore "assets,images,static,node_modules" --no-empty

      # 若采用自定义脚本，请改为：
      # - run: node scripts/build-sidebar.mjs

      - name: Commit if changed
        run: |
          if [[ -n "$(git status --porcelain docs/_sidebar.md)" ]]; then
            git config user.name  "gear-ci"
            git config user.email "g.zhanyu@ugmail.com"
            git add docs/_sidebar.md
            git commit -m "chore(sidebar): auto-update [skip ci]"
            git push
          else
            echo "No sidebar changes."
          fis